<% APP_NAME = 'tripmate' %>

development:
  adapter: postgresql
  encoding: unicode
  database: <%= APP_NAME %>_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= APP_NAME %>_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= APP_NAME %>_development
  pool: 5
  username: tripmate
  password: <%= ENV['TRIPMATE_DATABASE_PASSWORD'] %>
