<% APP_NAME = 'tripmate' %>

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: <%= APP_NAME %>_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: <%= APP_NAME %>_development
  pool: 5

staging:
  adapter: postgresql
  encoding: unicode
  database: <%= APP_NAME %>_staging
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= APP_NAME %>_development
  pool: 5
  username: tripmate
  password: <%= ENV['TRIPMATE_DATABASE_PASSWORD'] %>
